### ISSUE TITLE
Support YOLOv5 P6 models

### ISSUE THREAD

**Issue by mattpopovich** [zhiqwang/yolov5-rt-stack#144]
## 🐛 Bug

`torch.testing.assert_all_close()` fails for yolov5-v5.0 models. 
```
Traceback (most recent call last):
  File "convert_ultralytics_to_rt-stack.py", line 122, in <module>
    torch.testing.assert_allclose(
  File "/usr/local/lib/python3.8/dist-packages/torch/testing/__init__.py", line 215, in assert_allclose
    raise AssertionError("expected tensor shape {0} doesn't match with actual tensor "
AssertionError: expected tensor shape torch.Size([3]) doesn't match with actual tensor shape torch.Size([4])!
```
However, it does succeed for LibTorch C++ inference! So **I'd consider this low priority,** but wanted to make a note of it.

This might have something to do with the fact that v5.0 of yolov5 adds support for 4 output layers. However, this is the 3 output layer version (YOLOv5-P5 aka `yolov5s.pt`) vs the 4 output layer version (YOLOv5-P6 aka `yolov5s6.pt`). 

`torch.testing.assert_all_close()` succeeds for [yolov5-v4.0](https://github.com/ultralytics/yolov5/releases/download/v4.0/yolov5s.pt) models as well as LibTorch C++ inference. 

## To Reproduce
Follow the [how-to-align-with-ultralytics-yolov5.ipynb](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/how-to-align-with-ultralytics-yolov5.ipynb) notebook to the "Varify the detection results between yolort and ultralytics" section and use a [yolov5s-v5.0.pt](https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt) file for weights. 

## Expected behavior
The assert completes without error, as it does for yolov5-v4.0.pt weights. 

## Environment

<details><summary>Click to display environment</summary>
<p>

```
root@pc:~# python3 -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.8.0a0+56b43f4
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080
GPU 2: GeForce GTX 1080

Nvidia driver version: 460.84
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] pytorch-lightning==1.3.8
[pip3] torch==1.8.0a0+56b43f4
[pip3] torchmetrics==0.4.1
[pip3] torchvision==0.9.0a0+01dfa8e
[conda] Could not collect
```
</p>
</details>

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): 1.8.0 / 0.9.0
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): source / source
 - Python version: 3.8
 - CUDA/cuDNN version: 11.2
 - GPU models and configuration: 3x GeForce GTX 1080

**Comment by zhiqwang** [comment]
Hi @mattpopovich 

Thanks for reporting this! We haven't yet introduced this features of v5.0 from `YOLOv5`. In addition to this, in our local experiments we have found that using v5.0 of `YOLOv5` directly will introduce some minor numerical problems. At the moment we don't think this error is very critical and we haven't had time to find out exactly where the bug is coming from, and we will be working on this issue carefully in v0.5.0 of `yolort`.

**Comment by zhiqwang** [comment]
Hi @mattpopovich .

Finally we added support for P6 series model in #196 , and as such I'm closing this issue, feel free to create another ticket if you have more questions.
