### ISSUE TITLE
Exception: warning unhandled case: <class 'NoneType'>

### ISSUE THREAD

**Issue by rohanpawar294** [zhiqwang/yolov5-rt-stack#339]
### 🐛 Describe the bug

input_name = "input0"
shape_list = [(input_name, (1, 3, *input_shape))]
mod, params = relay.frontend.from_pytorch(script_module, shape_list
![Screenshot from 2022-03-01 12-30-11](https://user-images.githubusercontent.com/34226182/156120629-8deb7278-5029-4de4-91f0-a3e2aad8b556.png)
)

**Comment by zhiqwang** [comment]
Hi @rohanpawar294 , What are the versions of PyTorch, TorchVision and yolort you are using?

**Comment by zhiqwang** [comment]
Hi @rohanpawar294 ,

I'm closing this ticket due to inactivity for a long time, but feel free to reopen this or create another ticket if you have further questions.

**Comment by llurgent** [comment]
Hi！Have you solved this problem, and if so, can you guide me?
