### ISSUE TITLE
Windows TensorRT C++ example compatibility

### ISSUE THREAD

**Issue by zhiqwang** [zhiqwang/yolov5-rt-stack#384]
### 🐛 Describe the bug

The TensorRT example does not work properly in Windows system: <https://github.com/zhiqwang/yolov5-rt-stack/tree/main/deployment/tensorrt>.

```sh
mkdir build
cmake -G "Visual Studio 16 2019" -DTENSORRT_DIR="D:\TensorRT-8.2.4.2" -DOpenCV_DIR="C:\lib\install\opencv" ..
```

**Comment by IamNaQi** [comment]
![image](https://user-images.githubusercontent.com/76849182/163107245-cb764954-bb6c-4a00-9325-483c963b02dc.png)
`  Checking Build System
  Building Custom Rule C:/Users/Naqi/Desktop/yolov5-rt-stack-main/deployment/tensorrt/CMakeLists.txt
cl : command line error D8021: invalid numeric argument '/Wextra' [C:\Users\Naqi\Desktop\yolov5-rt-stack-main\deploymen
t\tensorrt\build\yolort_trt.vcxproj]
`

In my case cmake generate a VS project successfully  but raise up issue on build command
`cmake -G "Visual Studio 16 2019" -DTENSORRT_DIR="D:\TensorRT-8.4.0.6\lib" -DOpenCV_DIR="C:\lib\install\opencv" .. && **cmake --build .`**

**Comment by zhiqwang** [comment]
Hi @IamNaQi ,

These error is expected now, as you can see the CMakeList is not yet compatible with the Windows system now

https://github.com/zhiqwang/yolov5-rt-stack/blob/a6a08dd4b6ac5c24bf0275cbc1701ff561274ae0/deployment/tensorrt/CMakeLists.txt#L14-L16

**Comment by zhiqwang** [comment]
Hi @IamNaQi 

As #389 is merged now, I guess you can use the yolort to build TensorRT YOLOv5 on Windows System now, see https://github.com/zhiqwang/yolov5-rt-stack/tree/main/deployment/tensorrt for more details.

**Comment by IamNaQi** [comment]
@zhiqwang thank you so much for your great help and your precious  time. I will try it and let you know

**Comment by IamNaQi** [comment]
#### Thanks again,
Issue to getting CUDA libs has been resolve with your  new  [cmake list](https://github.com/zhiqwang/yolov5-rt-stack/blob/main/deployment/tensorrt/CMakeLists.txt), and Issue of result in C++ inference is also been resolved.
That was my mistake I am using RTX 3060 but CUDA version was installed 10.2 which is not compatible with RTX 3060. I just update it to CUDA 11.6 and build with new cmake with Visual Studio 2019.
