### ISSUE TITLE
No CUDA toolset found.

### ISSUE THREAD

**Issue by wangtianlong1994** [zhiqwang/yolov5-rt-stack#393]
### 🐛 Describe the bug

When I perform：
 cmake -D TENSORRT_DIR=D:\TensorRT-8.2.4.2 -D OpenCV_DIR="D:/opencv4.5.4/opencv/build" -D CUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.4" ..
report an error。

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
CMake Error at D:/cmake-3.23.1-windows-x86_64/share/cmake-3.23/Modules/CMakeDetermineCompilerId.cmake:491 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  D:/cmake-3.23.1-windows-x86_64/share/cmake-3.23/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  D:/cmake-3.23.1-windows-x86_64/share/cmake-3.23/Modules/CMakeDetermineCompilerId.cmake:59 (__determine_compiler_id_test)
  D:/cmake-3.23.1-windows-x86_64/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:339 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "D:/yolov5-rt-stack-main/deployment/tensorrt/build/CMakeFiles/CMakeOutput.log".

 I have set CUDA system variables，At the same time, I have specified cudA installation directory, but I still cannot find CUDA. I hope to get your help. This problem has bothered me for two days, thank you very much.  

Whether using CMD or Powershell, administrator or non-administrator, tensorrt or Oencv address change, it does not work. 

Replace the command:
![捕获](https://user-images.githubusercontent.com/48201258/164959906-321278a7-bee5-4170-a30f-969c88933ad0.PNG)
CMakeCache :
![捕获1](https://user-images.githubusercontent.com/48201258/164959909-5a36a4df-2560-429c-85df-77952908e54c.PNG)
The environment variable:
![捕获2](https://user-images.githubusercontent.com/48201258/164959922-37ee9101-838e-4922-b423-a7f4b57d68fa.PNG)
![捕获3](https://user-images.githubusercontent.com/48201258/164959937-75f9a364-4437-4e56-903f-403b80961b06.PNG)
Cuda, tensorRT, and OpencV installation paths:
![捕获4](https://user-images.githubusercontent.com/48201258/164960049-e5c2ab79-2dd1-4af7-9b3e-4d1973e1d219.PNG)
![捕获5](https://user-images.githubusercontent.com/48201258/164960054-3a8cd622-928e-446e-a0ed-13b3204c8fe6.PNG)
![捕获6](https://user-images.githubusercontent.com/48201258/164960060-86892ba4-20f9-45cb-b6bd-885698ec8813.PNG)

Thank you again for your help

### Versions

PS D:\yolov5-rt-stack-main\deployment\tensorrt\build> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_22:11:21_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0

**Comment by wangtianlong1994** [comment]
Thank you for your help. I put these four files under the path 
C: Program Files\NVIDIA GPU Computing Toolkit \CUDA\v11.1\ Extras \ Visual_studio_integration \MSBuildExtensions 
Copied to the 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\ buildcustomization 
Problem solved.

**Comment by zhiqwang** [comment]
Hi @wangtianlong1994 , Although I have not helped you, very glad to know that you have solved this issue!
