### ISSUE TITLE
Not getting prediction on custom yolov5s trained model 

### ISSUE THREAD

**Issue by suyashhchougule** [zhiqwang/yolov5-rt-stack#400]
### 🐛 Describe the bug

I have trained  custom yolov5s model on a single class dataset using instruction from [here](https://github.com/ultralytics/yolov5)
then I exported custom traied model in tensorrt engine using `export.py` from the samee repo
It works properly and gives correct prediction with python inference
But when I use cpp I get the following output :
The comand I used `./yolort_trt -i ./img.jpg -m best.engine -c ../custom.names`
output 
```
Loading engine from file: /home/suyash/yolov5/model/best.engine
3: Cannot find binding of given name: num_detections
3: Cannot find binding of given name: detection_boxes
3: Cannot find binding of given name: detection_scores
3: Cannot find binding of given name: detection_classes
  Bind[0] {Name:images, Datatype:0, Shape:(1,3,320,576,)}
  Bind[1] {Name:output, Datatype:0, Shape:(1,11340,6,)}
Detected 0 objects
```

### Versions

Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.21.2
Libc version: glibc-2.25

Python version: 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.9.253-tegra-aarch64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 10.2.300
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0
[pip3] torch-tensorrt==1.1.0a0+733a4b1c
[pip3] torchvision==0.11.1
[conda] numpy                     1.20.3           py37h603c2a0_0    conda-forge

**Comment by suyashhchougule** [comment]
> Hi @suyashhchougule ,
> 
> The exported ONNX models via yolort and yolov5 are not same, please use the following command to export the ONNX model and TensorRT serialized engine, see https://github.com/zhiqwang/yolov5-rt-stack/tree/main/deployment/tensorrt#usage and https://zhiqwang.com/yolov5-rt-stack/notebooks/onnx-graphsurgeon-inference-tensorrt.html for more details.
> 
> ```shell
> python3 tools/export_model.py --checkpoint_path {path/to/your/best.pt} --include engine
> ```

Trying to export model, getting following error 
`RuntimeError: yolort.relay.trt_graphsurgeon.__init__ requires module: onnx_graphsurgeon`

**Comment by zhiqwang** [comment]
Please use the following commands to install `onnx_graphsurgeon`:

```sh
python3 -m pip install onnx_graphsurgeon --index-url https://pypi.ngc.nvidia.com
```

And see https://zhiqwang.com/yolov5-rt-stack/notebooks/onnx-graphsurgeon-inference-tensorrt.html for more details.

**Comment by zhiqwang** [comment]
Seems that you didn't install `yolort`, please use the command below to install:

```sh
python3 -m pip install yolort==0.6.3
```

And you should also install `torch` and `torchvision` firstly to use the `yolort` Python interface, see https://pytorch.org/blog/running-pytorch-models-on-jetson-nano/ for more details.

**Comment by zhiqwang** [comment]
We currently do not officially support Jetson platform, which involves some dependencies of `torch` (see https://github.com/zhiqwang/yolov5-rt-stack/discussions/381#discussioncomment-2546007 for more details) and testing on the C++ interface.

I believe this issue is resolved now. I currently do not have the Jetson equipment and time to do such support, you can open a new ticket labeled enhancement [at here](https://github.com/zhiqwang/yolov5-rt-stack/issues/new?assignees=&labels=&template=feature-request.yml) if you have more questions about the usage of Jetson.

**Comment by youngjae-avikus** [comment]
@zhiqwang 

I think I can use it only with fp32, how can I use it with Fp16?
