### ISSUE TITLE
 module 'yolort' has no attribute 'utils'

### ISSUE THREAD

**Issue by beyondli** [zhiqwang/yolov5-rt-stack#465]
### 🐛 Describe the bug

I install yolort in python3.6 with pip3, successfully installed, but test import yolort failed,but on python3.8 import ok
My question is does yolort can not run on python3.6, if so ,can I modify code to fix it on python3.6??

### Versions
Sorry, collect env sh can not run on my host, cased by some link failed connect, I just copy pip3 list for your reference
pytools              2021.2.7
pytz                 2018.3
PyYAML               6.0
pyzmq                22.2.1
qtconsole            5.1.1
QtPy                 1.9.0
requests             2.26.0
rich                 12.6.0
scikit-build         0.11.1
scikit-learn         0.24.2
scipy                1.5.4
Send2Trash           1.7.1
setuptools           57.4.0
six                  1.16.0
tabulate             0.8.10
tensorboard          1.15.0
tensorflow           1.15.5+nv21.7
tensorflow-estimator 1.15.1
termcolor            1.1.0
terminado            0.10.1
testpath             0.5.0
thop                 0.1.1.post2209072238
threadpoolctl        2.2.0
torch                1.9.0
torchaudio           0.9.0a0+33b2469
torchvision          0.10.0a0+300a8a4
tornado              6.1
tqdm                 4.64.1
traitlets            4.3.3
typing_extensions    4.1.1
unattended-upgrades  0.1
urllib3              1.26.6
wcwidth              0.2.5
webencodings         0.5.1
Werkzeug             2.0.1
wheel                0.36.2
widgetsnbextension   3.5.1
wrapt                1.12.1
yolort               0.6.3                /usr/local/lib/python3.6/dist-packages
zipp                 3.5.0

![image](https://user-images.githubusercontent.com/11239010/196984452-f887e420-8f8a-4fe4-b773-292cbbb8b27d.png)

thanks any help!

**Comment by zhiqwang** [comment]
And you can see more details https://github.com/zhiqwang/yolov5-rt-stack/issues/429 .

**Comment by beyondli** [comment]
Hi zhiqwang,
I tried source code compile, but same issue still exist on py3.6, does any branch is directly based on py3.6?

**Comment by beyondli** [comment]
Hi zhiqwang,
I reinstall my system and use source compile, it is ok now ,thanks!
