### ISSUE TITLE
Can bbox coordinates be negative in yolo output?

### ISSUE THREAD

**Issue by youngjae-avikus** [zhiqwang/yolov5-rt-stack#479]
https://github.com/zhiqwang/yolov5-rt-stack/blob/b7cb695beacec273ea97cc0e3732797580ef37b5/deployment/tensorrt/main.cpp#L420-L423

Can the yolo output x coordinates (detection_boxes[4 * i]) be negative -0.0xxxx?

**Comment by zhiqwang** [comment]
Yes, I think it's possible, it depands on the inference results of YOLOv5 models.

**Comment by youngjae-avikus** [comment]
> Yes, I think it's possible, it depands on the inference results of YOLOv5 models.

In the experiment, the box.x value will have a - value, so there will be no problem if I proceed with **clip (n, 0, max),** right?

**Comment by zhiqwang** [comment]
Yep, you can filter the negative coordinates according your needs.

**Comment by youngjae-avikus** [comment]
@zhiqwang 
Thank you for your advice

**Comment by zhiqwang** [comment]
You're welcome and also thank you for your feedback.

In contrast, like some functions in OpenCV, they will automatically do some filtering of the coordinates outside the actual resolution of the image. We may also support similar features in the future.

**Comment by youngjae-avikus** [comment]
@zhiqwang 

https://github.com/zhiqwang/yolov5-rt-stack/blob/b7cb695beacec273ea97cc0e3732797580ef37b5/deployment/tensorrt/main.cpp#L63-L64

In this example, fortunately, you did int casting right away in visualize, so there was no problem. 
but I'd like you to point this out.
