### ISSUE TITLE
Support ultralytics released v4.0 stacks

### ISSUE THREAD

**Issue by zhiqwang** [zhiqwang/yolov5-rt-stack#49]
## 🚀 Feature

**ultralytics** has already released the v4.0 model checkpoints [here](https://github.com/ultralytics/yolov5/releases/tag/v4.0), it's time to support this version.

## Pitch

I've reserved interface to support the v4.0 version, such as

https://github.com/zhiqwang/yolov5-rt-stack/blob/f34b032ea3755f62a3fe7949a613043ebbed5586/models/darknet.py#L69-L70

and

https://github.com/zhiqwang/yolov5-rt-stack/blob/f34b032ea3755f62a3fe7949a613043ebbed5586/models/path_aggregation_network.py#L52-L53

But there are other parts like the activation function that need to be compatible.

**Comment by priya-dwivedi** [comment]
@zhiqwang - Awesome repo. We are looking to convert our Yolo v5 4.0 version model. Do you know when v 4.0 support will be available?

**Comment by zhiqwang** [comment]
Hi @priya-dwivedi

Thanks for your attention here, hope to finish this next Monday.

**Comment by zhiqwang** [comment]
Hi @priya-dwivedi ,

I've submitted a PR #66 for supporting v4.0, now I've only added the `yolov5s`, `yolov5m` and `yolov5l`. Can you tell me the information of the model you are using, such as `num_classes` and the architecture (`yolov5s` or `yolov5m`)?.

**Comment by priya-dwivedi** [comment]
Thanks @zhiqwang . I am using `yolov5s`. I will test out my model tomorrow.

**Comment by zhiqwang** [comment]
Hi @priya-dwivedi ,

I've refactored the checkpoint updating scripts, and now you can just run:

```python
from yolort.utils import update_module_state_from_ultralytics

# Update module state from ultralytics
model = update_module_state_from_ultralytics(arch='yolov5s', version='v4.0')
# Save updated module
torch.save(model.state_dict(), 'yolov5s_updated.pt')
```

The test all pass, and as such I'm closing this issue, but let me know if you have further questions.

**Comment by priya-dwivedi** [comment]
@zhiqwang - Thanks for the code push. We are able to convert our custom pytorch model to the yolov5-rt format using your suggestion above. However when we try to convert the pytorch model to ONNX using the command below, we get an error

Method for conversion to ONNX:

```torch.onnx.export(model,               # model being run
                  tensor,                    # model input (or a tuple for multiple inputs)
                  "best.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  #opset_version=10,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input' : {0 : 'batch_size'},    # variable lenght axes
                                'output' : {0 : 'batch_size'}})```

Error: `RuntimeError: step!=1 is currently not supported`
I will really appreciate any suggestions from you.

**Comment by zhiqwang** [comment]
@priya-dwivedi - I guess that this is because the ops torch.SiLU, torch.onnx didn’t support this ops now, I will add a deploy friendly for ops soon.

**Comment by priya-dwivedi** [comment]
Thanks @zhiqwang

**Comment by zhiqwang** [comment]
Hi @priya-dwivedi , I’ve created a new issue to trace on ONNX export of the 4.0 release, Let’s move the discussion there.
