### ISSUE TITLE
Does the tvm based CPU get accelerated?

### ISSUE THREAD

**Issue by jinfagang** [zhiqwang/yolov5-rt-stack#54]
Hi, just wonder tvm based deployed model can get accelerated or not?
Compare with vanilla pytorch CPU or onnxruntime or OpenVINO?

**Comment by zhiqwang** [comment]
Hi @jinfagang

Thanks for your attention here!

At that time, my plan is to let each side could compile and infer firstly, and because of time limited, I have not carefully compared the time of each side of `libtorch`, `onnxruntime` and `tvm`. (I have the plan to support `openvino`, also for the time limited, I didn't do it now).

Now, I'm writing and refactoring the trainer, after this is done, I will add the document of time consuming and comparison.

BTW, we are welcome for contribution in any ways.

**Comment by zhiqwang** [comment]
And I've uploaded the notebooks of `tvm` compiling and inference [here](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-relay-inference-tvm.ipynb), within my current experience, the procedure of compiling will consume more time than `libtorch` or `onnxruntime`,  the procedure of inference seems normal.

This repo is my first glance on `tvm`, and I will do more experiments on it.

**Comment by jinfagang** [comment]
@zhiqwang That's weried, tvm should be faster if compares on same CPU device? at least should faster than onnxruntime if chosen CPU as provider.

**Comment by zhiqwang** [comment]
> tvm should be faster if compares on same CPU device? at least should faster than onnxruntime if chosen CPU as provider.

Hi @jinfagang , I agree with you on this point, and this is my goal. The current realization on the `tvm` backend is only the initial attempt, let us do more efforts to achieve this goal!

**Comment by zhiqwang** [comment]
Hi @jinfagang 

I've added a rough comparison of inference time consumed on Jupyter notebook (iPython).

- On the onnxruntime backend,

  ```shell
  CPU times: user 2.04 s, sys: 0 ns, total: 2.04 s
  Wall time: 55.8 ms
  ```

- On the tvm backend,

  ```shell
  CPU times: user 528 ms, sys: 364 ms, total: 892 ms
  Wall time: 22.3 ms
  ```

You could check the latest updated [notebook](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-relay-inference-tvm.ipynb) for more details.

BTW, the displayed time of the onnxruntime [notebook](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-onnx-inference-onnxruntime.ipynb) is on GPU, I just test it locally.

Although this comparison is a bit rough, but we could come to this conclusion that `tvm` will increase inference speed on CPU device.
