### ISSUE TITLE
Add export friendly institutions of torch.SiLU

### ISSUE THREAD

**Issue by zhiqwang** [zhiqwang/yolov5-rt-stack#68]
To support exporting to ONNX and TVM of the upstream YOLOv5 4.0 releases.

_Originally posted by @priya-dwivedi in https://github.com/zhiqwang/yolov5-rt-stack/issues/49#issuecomment-783539183_

**Comment by zhiqwang** [comment]
Hi @priya-dwivedi , I've added the export friendly substitutions for SiLU, you can found it in ultralytics/yolov5 [here](https://github.com/ultralytics/yolov5/blob/cc79f3a9ea5d927475e7b896b18aa998c6e70795/utils/activations.py#L8-L12).
'
Now I've added two other parameters `upstream_version` and `export_friendly`. `upstream_version` is for determining the upstream YOLOv5 version and `export_friendly` is for deciding whether to use (ONNX/TVM) export friendly mode.

And the recommended exporting method to ONNX is through

```python
# Export to ONNX model
torch.onnx.export(
    model,
    (images,),
    export_onnx_name,
    do_constant_folding=True,
    opset_version=_onnx_opset_version,
    dynamic_axes={"images_tensors": [0, 1, 2], "outputs": [0, 1, 2]}, 
    input_names=["images_tensors"],
    output_names=["outputs"],
)
```

You could also check the [notebook](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/export-onnx-inference-onnxruntime.ipynb) or the [unit-test](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/test/test_onnx.py) for detail.

As such, I'll be closing this issue, but thanks again for the bug found and let us know if you have any more thoughts / comments.

**Comment by priya-dwivedi** [comment]
@zhiqwang - This worked for us. Thanks a bunch for adding this. Great repo!
