### ISSUE TITLE
how inference torchscript

### ISSUE THREAD

**Issue by nobody-cheng** [zhiqwang/yolov5-rt-stack#80]
how inference torchscript

**Comment by nobody-cheng** [comment]
> Hi @nobody-cheng ,
> 
> Are you interested in the python side or the cpp side?
> 
> If you want to use python, you could check [this notebook](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/inference-pytorch-export-libtorch.ipynb), and if you are interested in the Cpp backend, you could check the [unit-test](https://github.com/zhiqwang/yolov5-rt-stack/tree/master/test/tracing), and we provided an C++ [example](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/deployment) of how to infer with the transformed torchscript model, but this example is a little outdated.
> 
> BTW the upstream PyTorch have refactored their interfaces of torchscript recently, I've only updated the [unit-test](https://github.com/zhiqwang/yolov5-rt-stack/tree/master/test/tracing) to PyTorch 1.8. The [example](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/deployment) in deployment only works in PyTorch 1.7.x. I will update the example in deployment to PyTorch 1.8 soon.

```python
# TorchScript export
print(f'Starting TorchScript export with torch {torch.__version__}...')
export_script_name = './checkpoints/yolov5/yolov5s.torchscript.pt'  # >>>>>>> ** Variable is not called **

model_script = torch.jit.script(model)
model_script.eval()
model_script = model_script.to(device)

x = img[None]
out = model(x)
out_script = model_script(x)
```

**Comment by zhiqwang** [comment]
Hi @nobody-cheng ,

This is the target file to be generated, customize the name or fell free to delete this line! If you want to save the generated torchscript model, you can do something as belows:

```python
traced_model.save(export_script_name)
```

**Comment by nobody-cheng** [comment]
> Hi @nobody-cheng ,
> 
> This is the target torchscript model to be generated. You can customize the name or fell free to delete this line! If you want to save the generated model, you can do something as following:
> 
> ```python
> model_script.save(export_script_name)
> ```

ths 
ultralytics/yolov5 code
```python
model.model[-1].export = False  # set
```
```
python models/export.py --weights ./runs/train/exp5/weights/best.pt --img 640 --batch 1
```
it work
