### ISSUE TITLE
Error when convert custom model 

### ISSUE THREAD

**Issue by stereomatchingkiss** [zhiqwang/yolov5-rt-stack#90]
Thanks, I train the yolov5 model on kaggle(v4.0), copy out the best.pt, use the yolov5 repo to save the state_dict of the model, else the torch.load will throw error **'ModuleNotFoundError: No module named 'models''**

```
import torch

from models.experimental import attempt_load

if __name__ == '__main__':
    model = attempt_load('best.pt', map_location='cpu')  # load FP32 model
    torch.save(model.state_dict(), 'bn.pt')
```

After that, convert the custom model by yolov5-rt-stack

```
import torch
from yolort.utils import update_module_state_from_ultralytics

# Update module state from ultralytics
model = update_module_state_from_ultralytics(arch='yolov5s', version='v4.0', custom_path_or_model = torch.load('./best.pt'), num_classes = 1)
# Save updated module
torch.save(model.state_dict(), 'yolov5s_updated.pt')
```

This time got error message 

 ```
model = update_module_state_from_ultralytics(arch='yolov5s', version='v4.0', custom_path_or_model = torch.load('./bn.pt'), num_classes = 1)
  File "C:\Users\yyyy\programs\Qt\3rdLibs\pytorch_projects\yolov5-rt-stack\yolort\utils\update_module_state.py", line 61, in update_module_state_from_ultralytics
    model = torch.hub.load(f'ultralytics/yolov5:{version}', 'custom', path_or_model=custom_path_or_model)
  File "C:\Users\yyyy\Anaconda3\envs\ppyolo\lib\site-packages\torch\hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\yyyy\Anaconda3\envs\ppyolo\lib\site-packages\torch\hub.py", line 399, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\yyyy/.cache\torch\hub\ultralytics_yolov5_v4.0\hubconf.py", line 123, in custom
    model = model['model']  # load model
KeyError: 'model'
```

Any clues how to solve this?Thanks

**Comment by zhiqwang** [comment]
Hi @stereomatchingkiss , I guess this is a restriction of loading Ultralytics's trained model, maybe you should move the converted scripts to root path of ultralytics/yolov5. Now `yolort` is a independent package, you can install `yolort` first following the instructions [here](https://github.com/zhiqwang/yolov5-rt-stack#installation-and-inference-examples).

**Comment by stereomatchingkiss** [comment]
>Maybe you could move the conversion scripts to root path of "ultralytics/yolov5" to make sure the trained model is loaded correctly. 

Thanks, done already, I can load the custom model  by following codes

```
import torch

from models.experimental import attempt_load

if __name__ == '__main__':
    model = attempt_load('best.pt', map_location='cpu')  # load FP32 model
    torch.save(model.state_dict(), 'bn.pt')
```

But I cannot convert the model by yolort

```
import torch
from yolort.utils import update_module_state_from_ultralytics

# Update module state from ultralytics
model = update_module_state_from_ultralytics(arch='yolov5s', version='v4.0', custom_path_or_model = torch.load('./best.pt'), num_classes = 1)
# Save updated module
torch.save(model.state_dict(), 'yolov5s_updated.pt')
```

**Comment by zhiqwang** [comment]
Got it! Try the following first

```python
from yolort.utils.update_module_state import ModuleStateUpdate

arch = 'yolov5_darknet_pan_s_r40'
set_fp16 = True

module_state_updater = ModuleStateUpdate(
    arch=arch,
    num_classes=1,
)

module_state_updater.updating(model)

if set_fp16:
    module_state_updater.model.half()

model = module_state_updater.model

# Save updated module
torch.save(model.state_dict(), 'yolov5s_updated.pt')
```

And I will add more unit-test/instructions for this issue.

**Comment by stereomatchingkiss** [comment]
Thanks for your helps, I guess you forgot to load the model

```
import torch
from yolort.utils import update_module_state_from_ultralytics
from yolort.utils.update_module_state import ModuleStateUpdate

arch = 'yolov5_darknet_pan_s_r40'
set_fp16 = True

module_state_updater = ModuleStateUpdate(
    arch=arch,
    num_classes=1,
)

model = torch.load('bn.pt') #forgot to load model?
module_state_updater.updating(model)

if set_fp16:
    module_state_updater.model.half()

model = module_state_updater.model

# Save updated module
torch.save(model.state_dict(), 'yolov5s_updated.pt')
```

PS : This solution  use fp16, but my card(gtx1060) do not support fp16

**Comment by zhiqwang** [comment]
Good catch! And I've fixed my the above scripts. Would you mind providing me with an image for testing?

> PS : This solution use fp16, but my card(gtx1060) do not support fp16

You can set `set_fp16 = False`.

**Comment by stereomatchingkiss** [comment]
> Good catch! And I've fixed my the above scripts. Would you mind providing me with an image for testing?

Thanks, image do you mean weights? I put them to [google drive](https://drive.google.com/file/d/17ITmWNyb2haxgS-qUK04Md8CiEpocHSJ/view) already.

**Comment by stereomatchingkiss** [comment]
Forgot to mention, this script has new error(try set_fp16 as False/True)

```
Traceback (most recent call last):
  File "convert_v5_models.py", line 22, in <module>
    module_state_updater.updating(model)
  File "C:\Users\yyyy\programs\Qt\3rdLibs\pytorch_projects\yolov5-rt-stack\yolort\utils\update_module_state.py", line 104, in updating
    state_dict = obtain_module_sequential(state_dict)
  File "C:\Users\yyyy\programs\Qt\3rdLibs\pytorch_projects\yolov5-rt-stack\yolort\utils\update_module_state.py", line 167, in obtain_module_sequential
    return obtain_module_sequential(state_dict.model)
AttributeError: 'collections.OrderedDict' object has no attribute 'model'
```

**Comment by zhiqwang** [comment]
> Thanks, image do you mean weights?
> this script has new error(try set_fp16 as False/True)

Thanks. I've downloaded the trained model weights, and it would be better if you could provide me a test picture, and I will try to debug this issue more carefully later!

**Comment by stereomatchingkiss** [comment]
> 
> 
> > image do you mean weights? I put them to google drive already.
> > this script has new error(try set_fp16 as False/True)
> 
> Thanks. I've downloaded the trained model weights, and it would be better if you could provide me a test picture, and I will try to debug this issue more carefully later!

I would like to, but I am using windows10 + anaconda, do requirements.txt works?Export by following

`conda list -e > req.txt`

[link of the file.](https://drive.google.com/file/d/1mkO6K8948rSJDmGKSbKGsNy6hlwRbqoT/view?usp=sharing)

**Comment by zhiqwang** [comment]
I would like to, but I am using windows10 + anaconda, do requirements.txt works?Export by following
It should be works as long as you could load the Ultralytics's trained model successfully.

EDIT: Sorry I changed the message you sent, and I have reverted it.

**Comment by stereomatchingkiss** [comment]
> 
> 
> > I would like to, but I am using windows10 + anaconda, do requirements.txt works? Export by following
> 
> It should be works as long as you could load the Ultralytics's trained model successfully.
> 

Thanks, yes, I can load the  Ultralytics's trained model successfully(v4.0).

> EDIT: Sorry I modified the message you sent, and I have reverted it.

No problem, thanks for your helps, this project save us lots of pain when export the pre-trained model.

**Comment by stereomatchingkiss** [comment]
> Currently only the torch and torchvision are restricted, the minimal version are 1.7.1 and 0.8.2 respectively.

Yes, the version I am using is 1.7.1 and 0.8.2

**Comment by zhiqwang** [comment]
Hi @stereomatchingkiss , I use the following scripts and it works for me. (And I'm testing on the master branch on ultralytics/yolov5.)

```python
from yolort.utils.update_module_state import ModuleStateUpdate

model = torch.hub.load(
    'ultralytics/yolov5',
    'custom',
    path_or_model='./checkpoints/custom/models/best.pt',
)

# Setup the module state updater
module_state_updater = ModuleStateUpdate(arch='yolov5_darknet_pan_s_r40', num_classes=1)
# Updating module state from dingyiwei
module_state_updater.updating(model)
# This is the updated model we want
module_updated = module_state_updater.model

# Save updated module state
torch.save(module_updated.state_dict(), 'yolotrs_updated.pt')
```

**Comment by stereomatchingkiss** [comment]
>But now I didn't know which datasets you are using, if you can provided a picture from the datasets, it would be more helpful.

Thanks, it works, it is a model for smoke/fire detection, only train with 1 epoch, may not help much.
You can try with this dataset--[kaggle](https://www.kaggle.com/phylake1337/fire-dataset)

Do it able to support yolov5m, yolov5l, yolov5x?

**Comment by stereomatchingkiss** [comment]
> if you can provided a picture from the datasets, it would be more helpful.

I though the image mean "[create-image-of-currently-installed-ubuntu-on-my-laptop](https://stackoverflow.com/questions/10966712/how-to-create-image-of-currently-installed-ubuntu-on-my-laptop)"

**Comment by zhiqwang** [comment]
> Do it able to support yolov5m, yolov5l, yolov5x?

It should be works for yolov5m and yolov5l, but it doesn't support for yolov5x now, but I think that it could work with minor fix (I think yolov5x is somewhat big). PRs are welcome here!

> I though the image mean "create-image-of-currently-installed-ubuntu-on-my-laptop", my bad, thanks for your helps again.

Haha, Never mind here.

**Comment by stereomatchingkiss** [comment]
>It should work for yolov5m and yolov5l, but it doesn't support for yolov5x now, but I think that it could work with minor fix (I think yolov5x is somewhat big). PRs are welcome here!

Thanks, fine with s,m,l.
Will open pull request if I found anything I could help.

**Comment by stereomatchingkiss** [comment]
The outputs are great, although not the same as yolov5, maybe some pre-processing/post-processing steps are different. Maybe you forgot to convert color space from bgr to rgb in your "inference-pytorch-export-libtorch.ipynb"?

**Comment by zhiqwang** [comment]
> The outputs are great, although not the same as yolov5, maybe some pre-processing/post-processing steps are different.

I think that it is caused by the different pre-processing operations. The post-processing is same as ultralytics/yolov5 (when w/o TTA augmentation). Before I uploaded a [notebook](https://github.com/zhiqwang/yolov5-rt-stack/blob/master/notebooks/load-model-as-ultralytics.ipynb) in order to verify the model inference and post-processing stages, this one is a bit outdated, I haven’t had time to update it. And I am plan to add a [dataloader](https://github.com/zhiqwang/yolov5-rt-stack/blob/5a56c16eac95b56cb74d4aedb0ad98634635f0eb/yolort/data/detection_pipeline.py#L20) in the [predict pipeline](https://github.com/zhiqwang/yolov5-rt-stack/blob/5a56c16eac95b56cb74d4aedb0ad98634635f0eb/yolort/models/yolo_module.py#L189) to make `yolort` detect the same results as ultralytics.

> Looks like you forgot to convert color space from bgr to rgb in your "inference-pytorch-export-libtorch.ipynb"?

In my impression, ultralytics uses the BGR channel as default, but I am not very sure and need a double check. And it seems that the default image dataloader are using the RGB channel, if you input the image path to model, and use `model.predict('image_path'), it will be wrong, here also needs further verification.

BTW, all PRs are welcome here.
