### ISSUE TITLE
Replace `print` with `logger`

### ISSUE THREAD

**Issue by zhiqwang** [zhiqwang/yolov5-rt-stack#94]
## 🚀 Feature

Replace `print` statements with Python `logging` library.

**Comment by itsabhianant** [comment]
Hi @zhiqwang ,

I would like to fix this issue but can you please be more descriptive of what is needed to be done?

**Comment by zhiqwang** [comment]
Hi @itsabhianant ,

First of all thank you for your interest and welcome.

Now here are a few places where print statements are used, I want to replace `print()` with the Python logging library to control the logging information and set the destination for the logs, refer [here](https://www.loggly.com/blog/4-reasons-a-python-logging-library-is-much-better-than-putting-print-statements-everywhere/).

For example:

https://github.com/zhiqwang/yolov5-rt-stack/blob/0248f9762ff25f71a08a1db4930222ea21112080/yolort/data/_helper.py#L37

If we want to use the logging library, we should change it to the following

```python
import logging

# Get the top-level logger object
log = logging.getLogger()
logger.info(f'Create a new directory: {data_path}')
```

**Comment by itsabhianant** [comment]
Ok, I got your point. Can you do one more favor by letting me know the files you want this change to be implemented?

**Comment by zhiqwang** [comment]
They mainly appear in this [file](https://github.com/zhiqwang/yolov5-rt-stack/blob/0248f9762ff25f71a08a1db4930222ea21112080/yolort/data/_helper.py), in addition, there are the following three:

https://github.com/zhiqwang/yolov5-rt-stack/blob/ff8f5063b9c02c867e44159812e4c0ab79924c04/test/common_utils.py#L133

https://github.com/zhiqwang/yolov5-rt-stack/blob/2aaee950aaf6f5731dc4b861016c49a7a8f890dd/yolort/utils/image_utils.py#L228

https://github.com/zhiqwang/yolov5-rt-stack/blob/7e5a3338213852c6109ad5e10ae19aaf8bfd184f/yolort/models/experimental.py#L129

**Comment by itsabhianant** [comment]
Ok I am working on this. It would be cool if you would assign this issue to me.
